sudo: false
language: android
jdk: oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-25

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25+, latest, cannot get more granular control than this
    # See https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943 for more
    # details.
    - platform-tools
    - build-tools-25.2.3
    - android-25
    - extra-android-m2repository

before_install:
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

licenses:
  - 'android-sdk-license-.+'
